### ISSUE TITLE
The after header UIX of this extension is adding a paragraph which can break the layout of the wiki

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-defaultPageTemplate#1]
This extension is introducing an information in the page in an UIX that injects the code in the after header extension point.
This code is generating a paragraph, which by default in XWiki skin has bottom margin (thus it takes space on the screen).
When other extensions are injected after header (such as a menu), since, without additional parameters, the UIX are not ordered, it is possible that the default page template extension comes first (before the menu) and introduces a visual bar of the color of the body background.

![image](https://user-images.githubusercontent.com/657716/64445866-b3869b00-d0d7-11e9-9e7d-514af1ba3756.png)

Even in the absence of another UIX , the paragraph that takes room on the screen is adding an extra space which makes the pages on which the UIX is present different, visually, from the other pages.

**Comment by oanalavinia** [comment]
After talking with @lucaa, I'm changing the fix for this issue since _input_ is already in a div (_headerglobal_)
